### ISSUE TITLE
load legfed_v1_0.L trees into test db for assessing behavior in systems

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/legfed_gene_families#8]
currently using lis-adf (127.0.0.7) on iastate servers.

**Comment by adf-ncgr** [comment]
@cann0010 first taste of new legfed_v1_0 trees in LIS phylotree interface:

![image](https://user-images.githubusercontent.com/2009605/31650646-96334854-b2d5-11e7-95e4-be63756492d5.png)

still work to do, but making progress.

**Comment by StevenCannon-USDA** [comment]
Nice.

**Comment by adf-ncgr** [comment]
OK, as per my mention in the meeting just now, if you are on the ISU network (ie the lis- subnet) you should be able to use the 127.0.0.7 host to explore the new family content through the website interface (not including use of lorax for now, but for trees, e.g. https://127.0.0.7/chado_phylotree/legfed_v1_0.L.160WY and using these assignments in the context viewer).  There are probably a few loose ends, but it should be largely functional as is; let me know if you run into anything I haven't noticed. I think before we decide on a timeline for release, we need to think about how this will propagate into the mines and lorax as well.
